# some global settings for GCC
COMP_FLAGS=-g -Wall

programs:
	gcc $(COMP_FLAGS) -o fahrceltab.out fahrceltab.c
	gcc $(COMP_FLAGS) -o celfahrtab.out celfahrtab.c

clean:
	rm -v fahrceltab.out celfahrtab.out
